name: Publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release zip
        run: |
          cd src
          zip -r ../releases/release.zip .

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v6.0.0
        with:
          file-path: releases/release.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT }}
          client-secret: ${{ secrets.SECRET }}
          refresh-token: ${{ secrets.TOKEN }}
          publish: true